# OldCombatMechanics Plugin by kernitus
#Bukkit Page: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics/
#Spigot Page: https://www.spigotmc.org/resources/oldcombatmechanics.19510/
#GitHub Page: https://github.com/kernitus/BukkitOldCombatMechanics/
# This is to disable the update checker
update-checker: true