main: kernitus.plugin.OldCombatMechanics.OCMMain
name: OldCombatMechanics
version: 0.2
author: kernitus
description: Reverts to the old combat system.
website: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics
load: POSTWORLD

commands:
  OldCombatMechanics:
   description: OldCombatMechanics's main command
   aliases: ocm