main: kernitus.plugin.OldCombatMechanics.OCMMain
name: OldCombatMechanics
version: 0.5
author: kernitus
description: Removes weapon cooldown in 1.9 and above
website: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics
load: POSTWORLD

commands:
  OldCombatMechanics:
   description: OldCombatMechanics's main command
   aliases: ocm